"""remove patient columns

Revision ID: 17341a6922c1
Revises: b17648bdc56d
Create Date: 2025-02-27 14:52:18.436266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17341a6922c1'
down_revision = 'b17648bdc56d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('chat_history')
        batch_op.drop_column('prompts')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompts', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('chat_history', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
